apiVersion: apps/v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: angular-app
      name: angular-app
      namespace: starwars
    spec:
      ports:
        - name: "4200"
          port: 4200
          targetPort: 4200
      selector:
        io.kompose.service: angular-app
    status:
      loadBalancer: {}



  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-db
      name: mysql-db
      namespace: starwars
    spec:
      ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
      selector:
        io.kompose.service: mysql-db
    status:
      loadBalancer: {}



  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: php-my-admin
      name: php-my-admin
      namespace: starwars
    spec:
      ports:
        - name: "8081"
          port: 8081
          targetPort: 80
      selector:
        io.kompose.service: php-my-admin
    status:
      loadBalancer: {}





  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: springboot-app
      name: springboot-app
      namespace: starwars
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: springboot-app
    status:
      loadBalancer: {}




  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: angular-app
      name: angular-app
      namespace: starwars
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: angular-app
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: angular-app
        spec:
          containers:
            - image: imagedockerpaas.azurecr.io/frontend:81fe8bc5fbfb5ffb5a5cd4047edfd79f5a674dc9
              name: angular-app
              ports:
                - containerPort: 4200
              resources: {}
          restartPolicy: Always
    status: {}




  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-db
      name: mysql-db
      namespace: starwars
    spec:
      replicas: 2
      selector:
        matchLabels:
          io.kompose.service: mysql-db
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: mysql-db
        spec:
          containers:
            - env:
                - name: MYSQL_DATABASE
                  value: crud-application
                - name: MYSQL_ROOT_PASSWORD
                  value: password
              image: mysql
              name: mysql-db
              ports:
                - containerPort: 3306
              resources: {}
              volumeMounts:
                - mountPath: /docker-entrypoint-initdb.d/dump.sql
                  name: mysql-db-claim0
          restartPolicy: Always
          volumes:
            - name: mysql-db-claim0
              persistentVolumeClaim:
                claimName: mysql-db-claim0
    status: {}




  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-db-claim0
      name: mysql-db-claim0
      namespace: starwars
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}




  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: php-my-admin
      name: php-my-admin
      namespace: starwars
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: php-my-admin
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: php-my-admin
        spec:
          containers:
            - image: phpmyadmin
              name: php-my-admin
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}





  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: springboot-app
      name: springboot-app
      namespace: starwars
    spec:
      replicas: 2
      selector:
        matchLabels:
          io.kompose.service: springboot-app
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yaml -o kubemanifets.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: springboot-app
        spec:
          containers:
            - env:
                - name: MYSQL_DATABASE
                  value: crud-application
                - name: MYSQL_HOST
                  value: mysql-db
                - name: MYSQL_PASSWORD
                  value: password
                - name: MYSQL_USER
                  value: root
              image: imagedockerpaas.azurecr.io/backend:81fe8bc5fbfb5ffb5a5cd4047edfd79f5a674dc9
              name: springboot-app
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

